/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_subject_ysh_core_HttpService */

#ifndef _Included_com_subject_ysh_core_HttpService
#define _Included_com_subject_ysh_core_HttpService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_subject_ysh_core_HttpService
 * Method:    getSign
 * Signature: (Landroid/content/Context;Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_subject_ysh_core_HttpService_getSign
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
